language: ruby
script: bundle exec rspec
rvm:
  - 2.5.0
  - 2.3.1
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
deploy:
  provider: script
  script: sh bin/package_push.sh
  on:
    branch: RD-1545/use_gemfury
