#!/usr/bin/env ruby

require "rails_jmeter"

if ARGV.size == 0
  RailsJmeter.load_jmeter_files
else
  load ARGV.first
end

RailsJmeter.test_suite.run(
  file: 'tmp/rails_jmeter.jmx',
  log: 'tmp/rails_jmeter.log',
  jtl: 'tmp/rails_jmeter.jtl',
  gui: true
)